from langchain_ollama import ChatOllama
import pandas as pd

VALID_LABELS = {"YES", "NO"}


model = ChatOllama(
    model="qwen3.5:9b",
    temperature=0.0,
    reasoning=False,
    num_ctx=512,
    num_thread=4,
    num_predict=256,
)

data = pd.read_csv("MMRAG/qwen4b_results.csv")

required_columns = {
    "question", "actual_ans", "mmrag_ans"
}
missing_columns = required_columns - set(data.columns)
if missing_columns:
    raise ValueError(f"Missing required columns: {sorted(missing_columns)}")

comparison_results = []

system_prompt = """You are a strict evaluator. 
You will be given -
1. A question
2. The actual answer to the question
3. The answer generated by MMRAG
You will determine if the MMRAG answer contains the actual answer to the question.
Reply with only one of these exact labels:
 - YES if the MMRAG answer contains the actual answer, otherwise NO.
 - NO if the MMRAG answer does not contain the actual answer.

"""

for index, row in data.iterrows():
    question = row["question"]
    actual_answer = row["actual_ans"]
    mmrag_answer = row["mmrag_ans"]

    prompt = f"Question: {question}\nActual Answer: {actual_answer}\nMMRAG Answer: {mmrag_answer}"

    messages = [
        ('system', system_prompt),
        ('user', prompt),
    ]

    response = model.invoke(messages)
    comparison_results.append(response.content.strip().upper())

    print(f"Processed question {index+1}/{len(data)} || Result: {comparison_results[-1]}")


print(comparison_results.count("YES")/len(comparison_results))
print(comparison_results.count("NO")/len(comparison_results))