from langchain_ollama import ChatOllama
import pandas as pd

VALID_LABELS = {"WITHOUT_ATTN_REALLOC", "WITH_ATTN_REALLOC", "BOTH", "NEITHER"}


model = ChatOllama(
    model="qwen3.5:9b",
    temperature=0.0,
    reasoning=False,
    num_ctx=512,
    num_thread=4,
    num_predict=256,
)

data = pd.read_csv("qwen_answers.csv")

required_columns = {
    "question",
    "actual_answer",
    "without_attn_realloc",
    "with_attn_realloc",
}
missing_columns = required_columns - set(data.columns)
if missing_columns:
    raise ValueError(f"Missing required columns: {sorted(missing_columns)}")

comparison_results = []

system_prompt = """You are a strict comparator. 
You will be given - 
1. A question
2. The actual answer to the question
3. the answer generated by a model without attention reallocation
4. the answer generated by a model with attention reallocation

You will compare the two generated answers with the actual answer and determine which one contains the answer to the question more accurately.

Reply with only one of these exact labels:
WITHOUT_ATTN_REALLOC
WITH_ATTN_REALLOC
BOTH
NEITHER
"""

for index, row in data.iterrows():
    question = row["question"]
    actual_answer = row["actual_answer"]
    without_attn_realloc_answer = row["without_attn_realloc"]
    with_attn_realloc_answer = row["with_attn_realloc"]

    prompt = f"Question: {question}\nActual Answer: {actual_answer}\nWithout Attention Reallocation Answer: {without_attn_realloc_answer}\nWith Attention Reallocation Answer: {with_attn_realloc_answer}"

    messages = [
        ('system', system_prompt),
        ('user', prompt),
    ]

    response = model.invoke(messages)
    comparison_results.append(response.content.strip().upper())

    print(f"Processed question {index+1}/{len(data)} || Result: {comparison_results[-1]}")


print(comparison_results.count("WITHOUT_ATTN_REALLOC")/len(comparison_results))
print(comparison_results.count("WITH_ATTN_REALLOC")/len(comparison_results))
print(comparison_results.count("BOTH")/len(comparison_results))
print(comparison_results.count("NEITHER")/len(comparison_results))